FROM balenalib/aarch64-debian:latest

COPY . /lauszus-blhost

RUN [ "cross-build-start" ]

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y build-essential libudev-dev
RUN apt-get install -y libstdc++6

RUN make -j$(nproc) -C /lauszus-blhost/validation/blhost/gcc
RUN strip /lauszus-blhost/validation/blhost/gcc/Release/blhost

RUN [ "cross-build-end" ]
