FROM balenalib/armv7hf-debian:stretch

COPY . /lauszus-blhost

RUN [ "cross-build-start" ]

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y build-essential libudev-dev

RUN make -j$(nproc) -C /lauszus-blhost/validation/blhost/gcc

RUN [ "cross-build-end" ]
